---
title: "Bandas de confianza"
output: html_document
---

```{r}


par(mfrow=c(1,1))
require(car)  # Debe instalar antes el paquete car
qqPlot(datos3$V20, pch=19, las=1, main='V20 para la bureta de 25 mL',
       xlab='Cuantiles teóricos', ylab='Cuantiles muestrales')
```
```{r}
data=datos3
mod1 <- lm(Nominal ~ V20, data=datos3)
predict(object=mod1, newdata=datos3, interval="confidence", level=0.95)
predict(object=mod1, newdata=datos3, interval="prediction", level=0.95)
```

```{r}
data=datos3
mod1 <- lm(Nominal ~ V20, data=datos3)
future_y <- predict(object=mod1, interval="prediction", level=0.95)
nuevos_datos <- cbind(datos3, future_y)
library(ggplot2)
ggplot(nuevos_datos, aes(x=V20, y=Nominal))+
    geom_point() +
    geom_line(aes(y=lwr), color="red", linetype="dashed") +
    geom_line(aes(y=upr), color="red", linetype="dashed") +
    geom_smooth(method=lm, formula=y~x, se=TRUE, level=0.95, col='blue', fill='pink2') +
    theme_light()

adj_r2 (datos3)

```

```{r}
regresion <- lm(datos3)
confint(regresion)
confint(regresion, level = 0.90)
```


```{r}
nuevos.volumenes <- data.frame(V20 = seq(5, 25
                      ))
# Grafico de dispersion y recta
plot(datos3, xlab='Volúmen nominal', ylab='V20')
abline(regresion)

# Intervalos de confianza de la respuesta media:
# ic es una matriz con tres columnas: la primera es la prediccion, las otras dos son los extremos del intervalo
ic <- predict(regresion, nuevos.volumenes, interval = 'confidence')
lines(nuevos.volumenes$V20, ic[, 3], lty = 2)
lines(nuevos.volumenes$V20, ic[, 3], lty = 2)

# Intervalos de prediccion
ic <- predict(regresion, nuevos.volumenes, interval = 'prediction')
lines(nuevos.volumenes$V20, ic[, 2], lty = 2, col = 'red')
lines(nuevos.volumenes$V20, ic[, 3], lty = 2, col = 'red')
```
```{r}
anova(regresion)

```

